name: flutter_compose_ui_modifiers
description: Flutter UI Modifiers is a collection of declarative widget modifiers to make your Flutter code shorter and linear.
version: 0.3.2
author: q1 <zonggeu@gmail.com>
homepage: https://github.com/ahyangnb/flutter_compose_ui_modifiers

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: