name: flutter_compose_ui_modifiers
description: Flutter UI Modifiers is a collection of declarative widget modifiers to make your Flutter code shorter and linear.
version: 0.4.3
homepage: https://github.com/ahyangnb/flutter_compose_ui_modifiers

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^8.2.0
  #A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.3.1
  get: ^4.6.5
  #Refresh the page data.
  easy_refresh: ^3.3.4
  pull_to_refresh: ^2.0.0
  #Log print.
  logger: ^2.0.2
  keyboard_height_plugin: ^0.0.2 # pre height of keyboard.
  #Stora data to local.
  get_storage: ^2.0.3
  #Parse the link in the text.
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.0 # Launch the external browser.
  mix: ^1.0.0
  #Get current device information from within the Flutter application.
  device_info_plus: ^10.0.1
  #A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^1.0.7
  #Get system folder.
  path_provider: ^2.1.2
  #On most operating systems, permissions aren't just granted to apps at install time. Rather,
  # developers have to ask the user for permission while the app is running.
  permission_handler: ^11.3.0
  #Show svg image.
  flutter_svg: ^2.0.10+1
  #Json to dart.
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images/