name: flutter_compose_ui_modifiers
description: Flutter UI Modifiers is a collection of declarative widget modifiers to make your Flutter code shorter and linear.
version: 0.3.8
homepage: https://github.com/ahyangnb/flutter_compose_ui_modifiers

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^8.2.0
  get: ^4.6.6
  #Refresh the page data.
#  easy_refresh: ^3.3.4
  pull_to_refresh: ^2.0.0
  #Log print.
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: