name: flutter_compose_ui_modifiers
description: Flutter UI Modifiers is a collection of declarative widget modifiers to make your Flutter code shorter and linear.
version: 0.3.8
homepage: https://github.com/ahyangnb/flutter_compose_ui_modifiers

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^8.2.0
  #A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: 3.3.1
  get: ^4.6.6
  #Refresh the page data.
  easy_refresh: ^3.3.4
  pull_to_refresh: ^2.0.0
  #Log print.
  logger: ^1.3.0
  keyboard_height_plugin: ^0.0.2 # pre height of keyboard.
  #Stora data to local.
  get_storage: ^2.0.3
  #Parse the link in the text.
  flutter_linkify: 6.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: