name: flutter_compose_ui_modifiers
description: Flutter UI Modifiers is a collection of declarative widget modifiers to make your Flutter code shorter and linear.
version: 0.3.7
homepage: https://github.com/ahyangnb/flutter_compose_ui_modifiers

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^8.2.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: